# __________________________________ CONTENTS ___________________________________
#
#    This is a workflow file for GitHub Actions that builds
#    distributable binaries for all major platforms.
# _______________________________________________________________________________

name: "Build release binaries"

run-name: "Build binaries with Clang"

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false # delivers feedback for all matrix combinations
      matrix:
        include:
          # Ubuntu x86-64
          - target  : ubuntu
            arch    : x86_64
            runner  : ubuntu-latest
            compiler: llvm
            preset  : clang-release
            config  : Release
          # MacOS x86-64
          - target  : macos
            arch    : x86_64
            runner  : macos-latest
            compiler: llvm
            preset  : clang-release
            config  : Release
          # FreeBSD x86-64
          # - target  : freebsd
          #   arch    : x86_64
          #   runner  : ubuntu-latest
          #   compiler: llvm
          #   preset  : clang-release
          #   config  : Release
          # Windows x86-64
          - target  : windows
            arch    : x86_64
            runner  : windows-latest
            compiler: msvc
            preset  : msvc-release
            config  : Release
    
    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      # - name: "Set up FreeBSD VM"
      #   uses: vmactions/freebsd-vm@v1
      #   if: ${{ matrix.target == 'freebsd' }}
      #   with:
      #     release: '14.2' # release from 2024.12.03
      #     usesh: true     # otherwise FreeBSD uses 'tcsh' shell
      #     prepare: pkg install -y cmake
      
      - name: Setup LLVM toolchain
        uses: aminya/setup-cpp@v1
        if: ${{ matrix.compiler == 'llvm' }}
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
      
      - name: "Configure CMake"
        run: cmake --preset=${{ matrix.preset }}
      
      - name: "Build the project"
        run: cmake --build --preset=${{ matrix.preset }} --config ${{ matrix.configuration }}
      
      - name: "Upload test artifacts"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "artifacts-${{matrix.target}}-${{matrix.arch}}"
          path: |
            build/
            !build/CMakeFiles/clang-build-profiler.dir
