# __________________________________ CONTENTS ___________________________________
#
#    This is a workflow file for GitHub Actions that builds
#    distributable binaries for all major platforms.
# _______________________________________________________________________________

name: "Build release binaries"

run-name: "Build binaries with Clang"

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false # delivers feedback for all matrix combinations
      matrix:
        include:
          # Ubuntu x86-64
          - os      : ubuntu-latest
            compiler: llvm
            preset  : clang-release
            config  : Release
            arch    : x64
          # Windows x86-64
          - os      : windows-latest
            compiler: msvc
            preset  : msvc-release
            config  : Release
            arch    : x64
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        
      - name: Setup LLVM toolchain
        uses: aminya/setup-cpp@v1
        if: ${{ matrix.compiler == 'llvm' }}
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
      
      - name: "Configure CMake"
        run: cmake --preset=${{ matrix.preset }}
      
      - name: "Build the project"
        run: cmake --build --preset=clang-release --config ${{ matrix.configuration }}
      
      - name: "Upload test artifacts"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "artifact-${{matrix.os}}-${{matrix.arch}}"
          path: |
            build/
            !build/CMakeFiles/clang-build-profiler.dir
