# __________________________________ CONTENTS ___________________________________
#
#    This is a workflow file for GitHub Actions that builds
#    distributable binaries for all major platforms.
# _______________________________________________________________________________

name: "Build release binaries"

run-name: "Build binaries with Clang"

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false # delivers feedback for all matrix combinations
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
        configuration:
          - Release
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        
      - name: Setup LLVM toolchain
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm
          vcvarsall: true
          cmake: true
          ninja: true
        
      # - name: "Setup Clang"
      #  uses: egor-tensin/setup-clang@v1
    
      # - name: "Setup LLVM"
      #   uses: KyleMayes/install-llvm-action@v2
      #   with:
      #     version: "21"
      
      - name: "Configure CMake"
        run: cmake --preset=clang-release
      
      - name: "Build the project"
        run: cmake --build --preset=clang-release --config ${{ matrix.configuration }}
      
      - name: "Upload test artifacts"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "artifact-${{matrix.os}}-${{matrix.cxx}}"
          path: |
            build/
            !build/CMakeFiles/clang-build-profiler.dir
