# __________________________________ CONTENTS ___________________________________
#
#    This is a workflow file for GitHub Actions that
#    builds distributable binaries for Windows x86-64.
# _______________________________________________________________________________

name: "Build: Windows x86-64"

run-name: "Release build for Windows x86-64"

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      - name: "Configure CMake"
        run: cmake --preset=msvc-release
      
      - name: "Build the project"
        run: cmake --build --preset=msvc-release --config Release
      
      - name: "Upload test artifacts"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "artifacts-windows-x86_64"
          path: |
            build/
            !build/CMakeFiles/clang-build-profiler.dir
